services:
  vncserver:
    build:
      context: ./vncserver
      dockerfile: dockerfile
    # GUI用に共有メモリ拡張
    shm_size: 256m
    init: true
    # NW
    hostname: vnc-server
    networks:
      - vnc_nw

  novncserver:
    build:
      context: ./novncserver
      dockerfile: dockerfile
    depends_on:
      - vncserver
    # NW
    hostname: novnc-server
    networks:
      - vnc_nw
    ports:
      - target: 6080
        published: 6080
    # FS
    environment:
      - VNC_SERVER_HOST=vnc-server

networks:
  vnc_nw:
