FROM ubuntu:latest

RUN apt-get update\
    && apt-get install -y --no-install-recommends\
    openssh-server\
    apache2\
    supervisor\
    && apt-get clean\
    && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /var/lock/apache2 /var/run/apache2 /var/run/sshd /var/log/supervisor

COPY ./supervisord.conf /etc/supervisor/conf.d/supervisord.conf

CMD ["/usr/bin/supervisord"]
