# https://docs.docker.com/compose/compose-file/
version: '3.8'
services:
  sample-container:
    container_name: sample
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true # -i
    tty: true # -t
    volumes:
      # https://docs.docker.com/compose/compose-file/#volumes
      - type: volume
        source: storage
        target: /mnt/share

volumes:
  # https://docs.docker.com/compose/compose-file/#volumes-top-level-element
  storage:
    name: ex-storage
    external: false # docker-compose管理外で作成されたならtrueを指定する
