FROM debian:bookworm-slim

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get -qq update \
    && DEBIAN_FRONTEND=noninteractive apt-get -qq install --no-install-recommends -y\
    # utility系のインストール
    sudo\
    peco\
    silversearcher-ag\
    vim\
    lsof \
    curl wget dnsutils iproute2 iputils-ping traceroute\
    # Windows System系
    dbus-x11 x11-utils x11-xserver-utils x11-apps\
    # VNC系
    xterm\
    tigervnc-standalone-server tigervnc-common tigervnc-xorg-extension tigervnc-viewer tigervnc-tools\
    # tightvncserver\
    xfonts-base\
    # Desktop Environment
    # ubuntu-gnome-desktop
    # xubuntu-desktop
    # xfce4 xfce4-goodies\
    lxde\
    # retry
    supervisor\
    && apt-get clean\
    && rm -rf /var/lib/apt/lists/*

WORKDIR /root
COPY ./.vnc/ .vnc/

# VNC
ENV VNC_PW vncserver
RUN echo -e "${VNC_PW}\n${VNC_PW}\n" | vncpasswd -f > ~/.vnc/passwd

# Supervisor
RUN groupadd supervisor
COPY ./supervisor/vncserver.conf /etc/supervisor/conf.d/vncserver.conf
RUN mkdir -p /var/run/supervisor\
    && chown -R :supervisor /var/run/supervisor\
    && chmod -R g+wr /var/run/supervisor\
    && chown -R :supervisor /etc/supervisor\
    && chmod -R g+wr /etc/supervisor\
    && chown -R :supervisor /var/log/supervisor\
    && chmod -R g+wr /var/log/supervisor

COPY ./start.sh start.sh
ENTRYPOINT [ "/usr/bin/supervisord" ]
