# https://docs.docker.com/compose/compose-file/
version: "3.8"
services:
  alpine:
    container_name: alpine
    build:
      context: .
      dockerfile: alpine.Dockerfile
    hostname: alpine
    stdin_open: true # -i
    tty: true # -t
  busybox:
    container_name: busybox
    build:
      context: .
      dockerfile: busybox.Dockerfile
    hostname: busybox
    stdin_open: true # -i
    tty: true # -t
  debian-slim:
    container_name: debian-slim
    build:
      context: .
      dockerfile: debian-slim.Dockerfile
    hostname: debian-slim
    stdin_open: true # -i
    tty: true # -t
  distroless:
    container_name: distroless
    build:
      context: .
      dockerfile: distroless.Dockerfile
    hostname: distroless
    stdin_open: true # -i
    tty: true # -t
