x-redis-definition: &redis_definition
  build:
    context: .
    dockerfile: Dockerfile
  restart: always
  stdin_open: true
  tty: true


services:
  redis_client:
    <<: *redis_definition
    # entrypoint: redis-cli --cluster create redis-1:6379 redis-2:6379 redis-3:6379 redis-4:6379 redis-5:6379 redis-6:6379 --cluster-replicas 1 --cluster-yes
    entrypoint: ["/bin/bash"]
    hostname: redis-client
    networks:
      - cache_nw
    depends_on:
      - redis_node_1
      - redis_node_2
      - redis_node_3
      - redis_node_4
      - redis_node_5
      - redis_node_6
  redis_node_1:
    <<: *redis_definition
    hostname: redis-node-1
    networks:
      - cache_nw
  redis_node_2:
    <<: *redis_definition
    hostname: redis-node-2
    networks:
      - cache_nw
  redis_node_3:
    <<: *redis_definition
    hostname: redis-node-3
    networks:
      - cache_nw
  redis_node_4:
    <<: *redis_definition
    hostname: redis-node-4
    stdin_open: true
    tty: true
    networks:
      - cache_nw
  redis_node_5:
    <<: *redis_definition
    hostname: redis-node-5
    networks:
      - cache_nw
  redis_node_6:
    <<: *redis_definition
    hostname: redis-node-6
    networks:
      - cache_nw
networks:
  cache_nw:

